In [ ]:
import numpy as np
import grakel
from grakel.datasets import fetch_dataset

from sage.all import graphs

from random_walk import RandomWalk, RandomWalkLabeled

# GraKel

In [2]:
# Загрузка данных
MUTAG = fetch_dataset("MUTAG", verbose=False)
G, y = MUTAG.data, MUTAG.target

# Датасет - список списков. 
# В каждом списке есть:
#   1. Множество ребер
#   2. Словарь с лейблами вершин
#   3. Словарь с лейблами ребер
print(len(G))
G[0]

188


[{(1, 2),
  (1, 6),
  (2, 1),
  (2, 3),
  (3, 2),
  (3, 4),
  (4, 3),
  (4, 5),
  (4, 10),
  (5, 4),
  (5, 6),
  (5, 7),
  (6, 1),
  (6, 5),
  (7, 5),
  (7, 8),
  (8, 7),
  (8, 9),
  (9, 8),
  (9, 10),
  (9, 14),
  (10, 4),
  (10, 9),
  (10, 11),
  (11, 10),
  (11, 12),
  (12, 11),
  (12, 13),
  (13, 12),
  (13, 14),
  (13, 15),
  (14, 9),
  (14, 13),
  (15, 13),
  (15, 16),
  (15, 17),
  (16, 15),
  (17, 15)},
 {1: 0,
  2: 0,
  3: 0,
  4: 0,
  5: 0,
  6: 0,
  7: 0,
  8: 0,
  9: 0,
  10: 0,
  11: 0,
  12: 0,
  13: 0,
  14: 0,
  15: 1,
  16: 2,
  17: 2},
 {(2, 1): 0,
  (1, 2): 0,
  (3, 2): 0,
  (2, 3): 0,
  (4, 3): 0,
  (3, 4): 0,
  (5, 4): 0,
  (4, 5): 0,
  (6, 5): 0,
  (5, 6): 0,
  (6, 1): 0,
  (1, 6): 0,
  (7, 5): 0,
  (5, 7): 0,
  (8, 7): 0,
  (7, 8): 0,
  (9, 8): 0,
  (8, 9): 0,
  (10, 9): 0,
  (9, 10): 0,
  (10, 4): 0,
  (4, 10): 0,
  (11, 10): 0,
  (10, 11): 0,
  (12, 11): 0,
  (11, 12): 0,
  (13, 12): 0,
  (12, 13): 0,
  (14, 13): 0,
  (13, 14): 0,
  (14, 9): 0,
  (9, 14): 0,
  

In [3]:



# Создание ядра случайных блужданий. Нормализация приведет нас к значениям от 0 до 1
rw_kernel = RandomWalk(n_jobs=6, normalize=True)
# То же ядро, но с учетом лейблов
rw_labeled_kernel = RandomWalkLabeled(n_jobs=6, normalize=True)

In [4]:
# Вычисление матрицы ядра
K = rw_kernel.fit_transform(G)
K.shape, K

((188, 188),
 array([[1.        , 0.99886967, 0.99886967, ..., 0.99889635, 0.99859397,
         0.9998275 ],
        [0.99886967, 1.        , 1.        , ..., 0.99997528, 0.99508343,
         0.9978516 ],
        [0.99886967, 1.        , 1.        , ..., 0.99997528, 0.99508343,
         0.9978516 ],
        ...,
        [0.99889635, 0.99997528, 0.99997528, ..., 1.        , 0.99505288,
         0.99786513],
        [0.99859397, 0.99508343, 0.99508343, ..., 0.99505288, 1.        ,
         0.99940326],
        [0.9998275 , 0.9978516 , 0.9978516 , ..., 0.99786513, 0.99940326,
         1.        ]], shape=(188, 188)))

In [5]:
K_labeled = rw_labeled_kernel.fit_transform(G)
K_labeled.shape, K_labeled

((188, 188),
 array([[1.        , 0.96991364, 0.96991364, ..., 0.96617682, 0.99745827,
         0.99025906],
        [0.96991364, 1.        , 1.        , ..., 0.9998307 , 0.95187855,
         0.99406358],
        [0.96991364, 1.        , 1.        , ..., 0.9998307 , 0.95187855,
         0.99406358],
        ...,
        [0.96617682, 0.9998307 , 0.9998307 , ..., 1.        , 0.94745215,
         0.9922426 ],
        [0.99745827, 0.95187855, 0.95187855, ..., 0.94745215, 1.        ,
         0.97875684],
        [0.99025906, 0.99406358, 0.99406358, ..., 0.9922426 , 0.97875684,
         1.        ]], shape=(188, 188)))

# Sage

In [6]:



G_1 = graphs.PetersenGraph()       # Граф Петерсена
G_2 = graphs.CompleteGraph(7)      # Полный граф K7
G_3 = graphs.CycleGraph(15)        # Цикл из 15 вершин
G_4 = graphs.RandomGNP(12, 0.4)    # Случайный граф по модели Эрдёша-Реньи
G_5 = graphs.RandomBarabasiAlbert(50, 2)
G_6 = graphs.RandomBipartite(50, 30, 0.6)
G_7 = graphs.RandomBlockGraph(5, 30)
G_8 = graphs.RandomChordalGraph(30)
G_9 = graphs.RandomBoundedToleranceGraph(50)
G_10 = graphs.RandomBicubicPlanar(50)

In [7]:
# Для ядра GraKel надо либо перевести графы в класс grakel.Graph ()
graphs_data = [
    grakel.Graph(G_1.to_dictionary()),
    grakel.Graph(G_2.to_dictionary()),
    grakel.Graph(G_3.to_dictionary()),
    grakel.Graph(G_4.to_dictionary()),
    grakel.Graph(G_5.to_dictionary()),
    grakel.Graph(G_6.to_dictionary()),
    grakel.Graph(G_7.to_dictionary()),
    grakel.Graph(G_8.to_dictionary()),
    grakel.Graph(G_9.to_dictionary()),
    grakel.Graph(G_10.to_dictionary()),
]

rw_kernel = RandomWalk(n_jobs=6, normalize=True)
K = rw_kernel.fit_transform(graphs_data)
K.shape, K

/Users/marioauditore/Desktop/HSE/Kernels/.conda/lib/python3.11/site-packages/grakel/kernels/kernel.py:202: RuntimeWarning: invalid value encountered in sqrt
  return km / np.sqrt(np.outer(self._X_diag, self._X_diag))


((10, 10),
 array([[ 1.00000000e+00,             nan,  6.12372436e-01,
         -3.81285629e-01,             nan,             nan,
                     nan,  2.14581442e-02,             nan,
          8.72091946e-01],
        [            nan, -1.00000000e+00,             nan,
                     nan, -1.08536240e+00, -1.29788350e+00,
         -1.26461265e+00,             nan, -6.66181625e-01,
                     nan],
        [ 6.12372436e-01,             nan,  1.00000000e+00,
          5.05230878e+01,             nan,             nan,
                     nan, -8.04433563e-01,             nan,
          8.86072019e-01],
        [-3.81285629e-01,             nan,  5.05230878e+01,
          1.00000000e+00,             nan,             nan,
                     nan, -1.80562281e+00,             nan,
         -7.16851741e-01],
        [            nan, -1.08536240e+00,             nan,
                     nan, -1.00000000e+00,  6.99741880e-01,
         -1.62905962e-01,             nan

In [8]:
# Либо подать ему например список из списков (длина не более 3 и не менее 1), в которых сидит множество ребер
graphs_data = [
    [set(G_1.edges(labels=False))],
    [set(G_2.edges(labels=False))],
    [set(G_3.edges(labels=False))],
    [set(G_4.edges(labels=False))],
    [set(G_5.edges(labels=False))],
    [set(G_6.edges(labels=False))],
    [set(G_7.edges(labels=False))],
    [set(G_8.edges(labels=False))],
    [set(G_9.edges(labels=False))],
    [set(G_10.edges(labels=False))],
]

rw_kernel = RandomWalk(n_jobs=6, normalize=True)
K = rw_kernel.fit_transform(graphs_data)
K.shape, K

/Users/marioauditore/Desktop/HSE/Kernels/.conda/lib/python3.11/site-packages/grakel/kernels/kernel.py:202: RuntimeWarning: invalid value encountered in sqrt
  return km / np.sqrt(np.outer(self._X_diag, self._X_diag))


((10, 10),
 array([[ 1.00000000e+00,  8.23824236e-02,  9.98311995e-01,
                     nan,             nan, -1.74458692e+00,
                     nan, -9.81820652e-03,             nan,
          9.81952191e-01],
        [ 8.23824236e-02,  1.00000000e+00,  1.02381819e-01,
                     nan,             nan,  2.59439042e+03,
                     nan,  1.82558129e+00,             nan,
          9.02013391e-02],
        [ 9.98311995e-01,  1.02381819e-01,  1.00000000e+00,
                     nan,             nan, -2.38369188e-04,
                     nan,  5.21005179e-03,             nan,
          1.00853840e+00],
        [            nan,             nan,             nan,
         -1.00000000e+00,  6.86988179e-01,             nan,
         -1.36865814e+09,             nan, -2.03842282e+09,
                     nan],
        [            nan,             nan,             nan,
          6.86988179e-01, -1.00000000e+00,             nan,
         -1.02982169e+10,             nan

# Networkx

In [9]:
import networkx as nx


# 3. Граф Уоттса-Строгаца (модель малого мира)
G_ws = nx.watts_strogatz_graph(n=20, k=4, p=0.3, seed=123)

# 4. Случайный геометрический граф (Гильберта)
G_geo = nx.random_geometric_graph(n=25, radius=0.2, seed=123)

# 5. Случайный регулярный граф
G_reg = nx.random_regular_graph(d=3, n=16, seed=123)

In [10]:
# Также можно передать в класс ребра
graphs_data = [
    grakel.Graph(G_ws.edges()),
    grakel.Graph(G_geo.edges()),
    grakel.Graph(G_reg.edges()),
]

rw_kernel = RandomWalk(n_jobs=6, normalize=True)
K = rw_kernel.fit_transform(graphs_data)
K.shape, K

((3, 3),
 array([[1.        , 0.79744919, 0.87799985],
        [0.79744919, 1.        , 1.00178431],
        [0.87799985, 1.00178431, 1.        ]]))